baseurl = "https://blog.himanshuanand.com/"
languageCode = "en-us"
title = "Himanshu Anand :: Threat Notes"
theme = "terminal"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true

# Clean post URLs
[permalinks]
  posts = "/:year/:month/:slug/"

# Feeds & outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]     # JSON is handy for client-side search later
  section = ["HTML", "RSS"]

# Taxonomies
[taxonomies]
  tag = "tags"
  series = "series"

[params]
  contentTypeName = "posts"
  themeColor = "green"

  showMenuItems = 2
  showLanguageSelector = false

  fullWidthTheme = false
  centerTheme = true

  showLastUpdated = true
  dateFormat = "2006-01-02"
  readingTime = true
  toc = true

  # Custom assets (put files under /static/)
  css = ["css/custom.css", "css/hl.css"]
  js  = ["js/copy-code.js"]

  description = "Practical threat hunting, web malware, and client-side security notes by Himanshu Anand."
  author = "Himanshu Anand"

  # Open Graph / X (Twitter) defaults
  images = ["/images/og/default.png"]  # create this image

# X (Twitter) cards
[params.twitter]
  creator = "anand_himanshu"    # your @ without @
  site    = "anand_himanshu"

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true

[languages]

  [languages.en]
    languageName = "English"
    title = "Himanshu Anand :: Threat Notes"
    subtitle = "Cybersecurity blog focused on threat hunting & web malware"
    keywords = "cybersecurity, threat intel, web malware, client-side security, magecart, bug bounty"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "himanshu@blog:~$"
      logoHomeLink = "/"

    # Header menu (adds a direct link to your X profile)
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "x"
        name = "X (Twitter)"
        url = "https://x.com/anand_himanshu"
        weight = 50
