baseurl = "https://blog.himanshuanand.com/"
languageCode = "en-us"
title = "Himanshu Anand :: Threat Notes"
theme = "terminal"
paginate = 10
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
  posts = "/:year/:month/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true
  dateFormat = "2006-01-02"
  readingTime = true
  toc = true

  css = ["css/custom.css", "css/hl.css"]
  js  = ["js/copy-code.js", "js/typing-logo.js", "js/search.js"]

  description = "Practical threat hunting, web malware, and client-side security notes by Himanshu Anand."
  author = "Himanshu Anand"
  images = ["/images/og/default.png"]

[params.twitter]
  creator = "anand_himanshu"
  site    = "anand_himanshu"

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Himanshu Anand :: Threat Notes"
    subtitle = "Cybersecurity blog focused on threat hunting & web malware"
    keywords = "cybersecurity, threat intel, web malware, client-side security, magecart, bug bounty"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "himanshu@blog:~$"
      logoHomeLink = "/"

	[languages.en.menu]
	  [[languages.en.menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 1
	  [[languages.en.menu.main]]
		identifier = "about"
		name = "About"
		url = "/about"
		weight = 10
	  [[languages.en.menu.main]]
		identifier = "search"
		name = "Search"
		url = "/search/"
		weight = 20
	  [[languages.en.menu.main]]
		identifier = "showcase"
		name = "Showcase"
		url = "/showcase/"
		weight = 30
	  [[languages.en.menu.main]]
		identifier = "x"
		name = "X (Twitter)"
		url = "https://x.com/anand_himanshu"
		weight = 40
